######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 28 12:36:45 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h mydialog.h
FORMS += mainwindow.ui mydialog.ui
SOURCES += main.cpp mainwindow.cpp mydialog.cpp
